### ISSUE TITLE
Pundle doesn't work with Node LTS

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#144]
According to https://nodejs.org/en/download/, the LTS version of node **"recommended for most users"** is v6.11.  That doesn't include `Object.values`, so this fails:

```
$ yarn run pundle -- --dev 
yarn run v0.24.6
$ $( yarn bin )/pundle --dev
node_modules/pundle-api/lib/file.js:37
var features = new Set(Object.values(FEATURES));
                              ^

TypeError: Object.values is not a function
    at Object.<anonymous> (node_modules/pundle-api/lib/file.js:37:31)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules/pundle-api/lib/file-chunk.js:16:13)
    at Module._compile (module.js:541:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Perhaps use a polyfill for Object.values?  Else, the required version of Node should be in the README.  😃

**Comment by steelbrain** [comment]
Will use a polyfill instead, totally forgot about this

**Comment by steelbrain** [comment]
Ended up replacing `Object.values` with `Object.keys` for same effect without polyfill, beta 25 is out
