### ISSUE TITLE
Npm 'github' fails on require

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#166]
```js
import Github from 'github'
```

Gives the error:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1254:5)
    at Object.<anonymous> (/Users/nw/projects/motion/pundle/packages/resolver-default/lib/index.js:177:35)
    at Generator.next (<anonymous>)
    at step (/Users/nw/projects/motion/pundle/packages/resolver-default/lib/index.js:27:191)
    at /Users/nw/projects/motion/pundle/packages/resolver-default/lib/index.js:27:361
    at <anonymous>
```

**Comment by natew** [comment]
Seems like it uses 'fs', and meant for node only. Moving to github.js instead!
