### ISSUE TITLE
Babel 7

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#176]
Just curious plans for support, tried running it and got:

```
Error: Babel not found in '/Users/nw/github/myapp' (tried babel-core)
    at /Users/nw/github/myapp/node_modules/pundle-transformer-babel/lib/index.js:65:17
    at Generator.next (<anonymous>)
    at step (/Users/nw/github/myapp/node_modules/pundle-transformer-babel/lib/index.js:15:221)
    at _next (/Users/nw/github/myapp/node_modules/pundle-transformer-babel/lib/index.js:15:409)
    at /Users/nw/github/myapp/node_modules/pundle-transformer-babel/lib/index.js:15:477
    at new Promise (<anonymous>)
    at /Users/nw/github/myapp/node_modules/pundle-transformer-babel/lib/index.js:15:97
    at Object.callback (/Users/nw/github/myapp/node_modules/pundle-transformer-babel/lib/index.js:92:9)
    at /Users/nw/github/myapp/node_modules/pundle-api/lib/context/index.js:172:44
    at Generator.next (<anonymous>)
```

**Comment by steelbrain** [comment]
Babel v7 is supported in Pundle. The default `create-pundle-react-app` config tries to load Babel 6, You can change that by

- Removing `.babelrc` and adding `babel.config.js`
- Adding `@babel/core` as a dev dependency to project
- Changing [this line](https://github.com/steelbrain/pundle/blob/952ddcd599e420e45e72600960eba43df578a0f5/packages/create-pundle-react-app/template/pundle.config.js#L8) in your config to `babel: 7`

**Comment by natew** [comment]
May be good to document this! Sorry for no PR

**Comment by natew** [comment]
Getting this after making the changes:

```
Error: Cannot find module 'babel-preset-env' from '/Users/nw/github/myapp'
- Did you mean "@babel/env"?
    at Function.module.exports [as sync] (/Users/nw/github/myapp/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/Users/nw/github/myapp/node_modules/@babel/core/lib/config/files/plugins.js:100:31)
    at resolvePreset (/Users/nw/github/myapp/node_modules/@babel/core/lib/config/files/plugins.js:57:10)
    at loadPreset (/Users/nw/github/myapp/node_modules/@babel/core/lib/config/files/plugins.js:76:20)
    at createDescriptor (/Users/nw/github/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:135:21)
    at items.map (/Users/nw/github/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:87:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/nw/github/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:87:29)
    at createPresetDescriptors (/Users/nw/github/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:79:10)
    at presets (/Users/nw/github/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:61:19)
```
