### ISSUE TITLE
Exit command not exiting

### ISSUE THREAD

**Issue by JacobBovee** [steelbrain/pundle#33]
When you type exit in motion you get this error. 

```
Uncaught Exception TypeError: Cannot read property 'dispose' of undefined
    at /Users/macbook/Desktop/motion/motion/packages/motion/lib/index.js:53:12
    at Emitter.emit (/Users/macbook/Desktop/motion/motion/packages/motion/node_modules/sb-event-kit/lib/emitter.js:78:28)
    at CLI.<anonymous> (/Users/macbook/Desktop/motion/motion/packages/motion/lib/cli/index.js:81:21)
    at CommandInstance.<anonymous> (/Users/macbook/Desktop/motion/motion/packages/motion/lib/cli/cli.js:54:29)
    at EventEmitter.session.execCommandSet (/Users/macbook/Desktop/motion/motion/packages/motion/node_modules/vorpal/dist/session.js:470:20)
    at EventEmitter.vorpal._exec (/Users/macbook/Desktop/motion/motion/packages/motion/node_modules/vorpal/dist/vorpal.js:956:18)
    at EventEmitter.vorpal._execQueueItem (/Users/macbook/Desktop/motion/motion/packages/motion/node_modules/vorpal/dist/vorpal.js:747:17)
    at EventEmitter.vorpal._queueHandler (/Users/macbook/Desktop/motion/motion/packages/motion/node_modules/vorpal/dist/vorpal.js:731:10)
    at EventEmitter.vorpal.exec (/Users/macbook/Desktop/motion/motion/packages/motion/node_modules/vorpal/dist/vorpal.js:678:10)
    at /Users/macbook/Desktop/motion/motion/packages/motion/node_modules/vorpal/dist/vorpal.js:621:10
```

**Comment by steelbrain** [comment]
This is a bug in babel's arrow function transpiler, we should work-it-around by compiling pundle with babel `6.7.2` or `6.7.5`, we should also be enforcing the same babel version in our `babel-pundle` package to make sure this doesn't break dependents
