### ISSUE TITLE
Installer doesn't work on docker

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/pundle#39]
```
⠋ Installing sb-pluralize[consistent-env] Unable to determine environment TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /app/node_modules/consistent-env/lib/index.js:39:40
    at new Promise (/app/node_modules/core-js/modules/es6.promise.js:193:7)
    at module.exports.async (/app/node_modules/consistent-env/lib/index.js:33:10)
    at /app/node_modules/sb-exec/lib/helpers.js:13:51
    at next (native)
    at step (/app/node_modules/sb-exec/lib/helpers.js:59:191)
    at /app/node_modules/sb-exec/lib/helpers.js:59:451
    at new Promise (/app/node_modules/core-js/modules/es6.promise.js:193:7)
Install sb-pluralize ✗
[Error: spawn npm ENOENT at exports._errnoException (util.js:953:11)]
[Error: Unable to resolve 'sb-pluralize' from '$root/helpers' at /app/node_modules/pundle/lib/path.js:59:15]
```

**Comment by steelbrain** [comment]
Fixed in v0.2.15
