### ISSUE TITLE
Fixing not found file error fails

### ISSUE THREAD

**Issue by natew** [steelbrain/pundle#72]
```
[Error: Cannot find module './logo' at $root/node_modules/macro-ui/lib/index.js:120:13]

# after fixing:

[Error: Module not found 'index.js' at getAllImports (/Users/nw/company/macro/apps/macro/node_modules/pundle/lib/helpers.js:314:15)]
[Error: Module not found 'index.js' at getAllImports (/Users/nw/company/macro/apps/macro/node_modules/pundle/lib/helpers.js:314:15)]
```

**Comment by steelbrain** [comment]
Fixed in Pundle [v2Alpha1](https://github.com/motion/pundle/releases/tag/v2.0.0-alpha1)
