### ISSUE TITLE
HMR presumes index.js in current folder

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#77]
```
  Pundle:Error Error: ENOENT: no such file or directory, stat '~/Projects/pundle/packages/test/index.js'
```

if I run `./devServer.js --entry --hmr ./src/index.js`.  `cd`ing into `src` first fixes it.

**Comment by steelbrain** [comment]
You might want to run `./devServer.js --entry ./src/index.js --hmr` instead, notice the ordering of -`--key value`

**Comment by appsforartists** [comment]
```
TypeError: this.config.pundle.entry.unshift is not a function
    at new Server (~/Projects/pundle/packages/dev/lib/index.js:49:32)
    at Object.<anonymous> (~/Projects/pundle/packages/test/devServer.js:35:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

:cry:

**Comment by steelbrain** [comment]
Oh boy, Pundle@1 might not be the most stable release ever. I can assure you tho that the upcoming v2 will be very stable, and precitable and will even have a `Pundleconfig.js` so you don't have to write the dev server logic in each project

**Comment by steelbrain** [comment]
Fixed in Pundle [v2Alpha1](https://github.com/motion/pundle/releases/tag/v2.0.0-alpha1)
